#este archivo define las rutas relativas a cada dataset que vayamos a usar


dataset:
  stress_data_path: "/dataset/EMA/response/Stress"
  social_data_path: "/dataset/EMA/response/Social"
  sleep_data_path: "/dataset/EMA/response/Sleep"
  class_data_path: "/dataset/EMA/response/Class"
  lab_data_path: "/dataset/EMA/response/Lab"
  conversation_data_path: "/dataset/sensing/conversation"
  activity_data_path: "/dataset/sensing/activity"
  bigfive_data_path: "/dataset/survey/BigFive.csv"
  flourishing_data_path: "/dataset/survey/FlourishingScale.csv"
  loneliness_data_path: "/dataset/survey/LonelinessScale.csv"
  users_chosen: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 55, 56, 57, 58, 59]
#  users_chosen: [4, 7, 8, 10, 14, 16, 17, 19, 22, 23, 24, 32, 33, 35, 36, 43, 44, 49, 51, 52, 53, 57, 58]
# nota los usuarios no seleccionados dan error en la extraccion de datos no meterlos.
# he aumentado los datos seleccionados debido a que varios modelos penalizaban estres 1 y 5 por falta de datos